# Conclusion

## Limitations

Some datasets contained city-wise information while all of the datasets contained state-wise information. To be consistent while generating conclusive arguments, we only decided to work on state-wise information for all datasets. There was no official Crime data with respect to the state Hawai and so we didn't take this state into consideration for our analysis. Since there wasn't any official Crime Data for the year 2021, we worked on the most recent dataset released by FBI with respect to the year 2020. Since for our analysis, we were trying to find out the correlation between vaccination density and the total crimes for the states, we assume that the the change in the total number of crimes for the year 2021 with respect to each state would not vary much from that of the previous year given the historical nature of crime associated with each state. And the conclusions we made in this respect could be related to the perception of the people on whether stepping out of their homes to take the vaccination would be safe in their neighborhood. Additionally, since it has only been a year after since the vaccination started and there have been many new variants of COVID-19 emerging such as the Delta variant and the Omicron, any conclusions that are made now could tend to change over a period of time given the dynamic nature of COVID-19.

## Scope of Future Work

More factors can be taken into consideration to derive a better conclusive argument for the various factors which influenced vaccination. Additionally, analysis on datasets where every data contains demographic details attached with it can also improve the quality of the analysis by giving us an idea of the perception of vaccination among different sections of people. We believe that the metric that we have defined currently for the vaccine wastage could be improved once official data regarding the same is made available. Using that, we could define our metric better and make our arguments more concrete and conclusive.

## Lessons Learned